In [2]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("uciml/iris")

print("Path to dataset files:", path)

c:\Users\Muhammad Faizan Ali\AppData\Local\Programs\Python\Python313\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


Path to dataset files: C:\Users\Muhammad Faizan Ali\.cache\kagglehub\datasets\uciml\iris\versions\2


Task 01: LOAD THE DATASET

i_ Load the CSV file using np.genfromtxt() or np.loadtxt() (skip the header if needed).

ii_ Slice out the numerical columns into a separate NumPy array (4 features only).

In [3]:
import numpy as np
dataSet = np.loadtxt('Iris.csv', delimiter=',', skiprows=1, usecols=(1, 2, 3, 4))
dataSet

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

iii_ Print the shape of the resulting NumPy array.

In [4]:
print(f"Shape of the resulting NumPy array is {dataSet.shape}")

Shape of the resulting NumPy array is (150, 4)


TASK 02: BASIC ARRAY OPERATION.

i_ Compute the mean, max, and min for each column.

In [5]:
print("mean per column:",np.mean(dataSet,axis=0))
print("max per column:",np.max(dataSet,axis=0))
print("min per column:",np.min(dataSet,axis=0))

mean per column: [5.84333333 3.054      3.75866667 1.19866667]
max per column: [7.9 4.4 6.9 2.5]
min per column: [4.3 2.  1.  0.1]


In [17]:
print(f"Standard Deviation per Column: {np.round(np.std(dataSet, axis=0),3)}")
print(f"Variance per Column: {np.round(np.var(dataSet, axis=0), 3)}")

Standard Deviation per Column: [0.825 0.432 1.759 0.761]
Variance per Column: [0.681 0.187 3.092 0.579]


In [19]:
normalized_dataSet = (dataSet - np.mean(dataSet)) / np.std(dataSet)
normalized_dataSet.round(2)

array([[ 0.83,  0.02, -1.05, -1.65],
       [ 0.73, -0.23, -1.05, -1.65],
       [ 0.63, -0.13, -1.1 , -1.65],
       [ 0.58, -0.18, -0.99, -1.65],
       [ 0.78,  0.07, -1.05, -1.65],
       [ 0.98,  0.22, -0.89, -1.55],
       [ 0.58, -0.03, -1.05, -1.6 ],
       [ 0.78, -0.03, -0.99, -1.65],
       [ 0.47, -0.29, -1.05, -1.65],
       [ 0.73, -0.18, -0.99, -1.7 ],
       [ 0.98,  0.12, -0.99, -1.65],
       [ 0.68, -0.03, -0.94, -1.65],
       [ 0.68, -0.23, -1.05, -1.7 ],
       [ 0.42, -0.23, -1.2 , -1.7 ],
       [ 1.18,  0.27, -1.15, -1.65],
       [ 1.13,  0.47, -0.99, -1.55],
       [ 0.98,  0.22, -1.1 , -1.55],
       [ 0.83,  0.02, -1.05, -1.6 ],
       [ 1.13,  0.17, -0.89, -1.6 ],
       [ 0.83,  0.17, -0.99, -1.6 ],
       [ 0.98, -0.03, -0.89, -1.65],
       [ 0.83,  0.12, -0.99, -1.55],
       [ 0.58,  0.07, -1.25, -1.65],
       [ 0.83, -0.08, -0.89, -1.5 ],
       [ 0.68, -0.03, -0.79, -1.65],
       [ 0.78, -0.23, -0.94, -1.65],
       [ 0.78, -0.03, -0.94, -1.55],
 

In [34]:
sepal_length = dataSet[:, 0]
print(sepal_length.reshape(150, 1))

[[5.1]
 [4.9]
 [4.7]
 [4.6]
 [5. ]
 [5.4]
 [4.6]
 [5. ]
 [4.4]
 [4.9]
 [5.4]
 [4.8]
 [4.8]
 [4.3]
 [5.8]
 [5.7]
 [5.4]
 [5.1]
 [5.7]
 [5.1]
 [5.4]
 [5.1]
 [4.6]
 [5.1]
 [4.8]
 [5. ]
 [5. ]
 [5.2]
 [5.2]
 [4.7]
 [4.8]
 [5.4]
 [5.2]
 [5.5]
 [4.9]
 [5. ]
 [5.5]
 [4.9]
 [4.4]
 [5.1]
 [5. ]
 [4.5]
 [4.4]
 [5. ]
 [5.1]
 [4.8]
 [5.1]
 [4.6]
 [5.3]
 [5. ]
 [7. ]
 [6.4]
 [6.9]
 [5.5]
 [6.5]
 [5.7]
 [6.3]
 [4.9]
 [6.6]
 [5.2]
 [5. ]
 [5.9]
 [6. ]
 [6.1]
 [5.6]
 [6.7]
 [5.6]
 [5.8]
 [6.2]
 [5.6]
 [5.9]
 [6.1]
 [6.3]
 [6.1]
 [6.4]
 [6.6]
 [6.8]
 [6.7]
 [6. ]
 [5.7]
 [5.5]
 [5.5]
 [5.8]
 [6. ]
 [5.4]
 [6. ]
 [6.7]
 [6.3]
 [5.6]
 [5.5]
 [5.5]
 [6.1]
 [5.8]
 [5. ]
 [5.6]
 [5.7]
 [5.7]
 [6.2]
 [5.1]
 [5.7]
 [6.3]
 [5.8]
 [7.1]
 [6.3]
 [6.5]
 [7.6]
 [4.9]
 [7.3]
 [6.7]
 [7.2]
 [6.5]
 [6.4]
 [6.8]
 [5.7]
 [5.8]
 [6.4]
 [6.5]
 [7.7]
 [7.7]
 [6. ]
 [6.9]
 [5.6]
 [7.7]
 [6.3]
 [6.7]
 [7.2]
 [6.2]
 [6.1]
 [6.4]
 [7.2]
 [7.4]
 [7.9]
 [6.4]
 [6.3]
 [6.1]
 [7.7]
 [6.3]
 [6.4]
 [6. ]
 [6.9]
 [6.7]
 [6.9]
 [5.8]

In [36]:
first_10 = dataSet[:10]
print(first_10)


[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]


In [37]:
filtered_flowers = dataSet[dataSet[:, 2] > 1.5]
print(filtered_flowers)


[[5.4 3.9 1.7 0.4]
 [4.8 3.4 1.6 0.2]
 [5.7 3.8 1.7 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [5.1 3.8 1.6 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.  1.3]
 [6.5 2.8 4.6 1.5]
 [5.7 2.8 4.5 1.3]
 [6.3 3.3 4.7 1.6]
 [4.9 2.4 3.3 1. ]
 [6.6 2.9 4.6 1.3]
 [5.2 2.7 3.9 1.4]
 [5.  2.  3.5 1. ]
 [5.9 3.  4.2 1.5]
 [6.  2.2 4.  1. ]
 [6.1 2.9 4.7 1.4]
 [5.6 2.9 3.6 1.3]
 [6.7 3.1 4.4 1.4]
 [5.6 3.  4.5 1.5]
 [5.8 2.7 4.1 1. ]
 [6.2 2.2 4.5 1.5]
 [5.6 2.5 3.9 1.1]
 [5.9 3.2 4.8 1.8]
 [6.1 2.8 4.  1.3]
 [6.3 2.5 4.9 1.5]
 [6.1 2.8 4.7 1.2]
 [6.4 2.9 4.3 1.3]
 [6.6 3.  4.4 1.4]
 [6.8 2.8 4.8 1.4]
 [6.7 3.  5.  1.7]
 [6.  2.9 4.5 1.5]
 [5.7 2.6 3.5 1. ]
 [5.5 2.4 3.8 1.1]
 [5.5 2.4 3.7 1. ]
 [5.8 2.7 3.9 1.2]
 [6.  2.7 5.1 1.6]
 [5.4 3.  4.5 1.5]
 [6.  3.4 4.5 1.6]
 [6.7 3.1 4.7 1.5]
 [6.3 2.3 4.4 1.3]
 [5.6 3.  4.1 1.3]
 [5.5 2.5 4.

In [38]:
row1 = dataSet[0]
row2 = dataSet[1]

euclidean_distance = np.linalg.norm(row1 - row2)
print("Euclidean Distance:", euclidean_distance)


Euclidean Distance: 0.5385164807134502


In [39]:
mean_sepal_width = np.mean(dataSet[:, 1])
count = np.sum(dataSet[:, 1] > mean_sepal_width)
print("Flowers with Sepal Width > Mean:", count)


Flowers with Sepal Width > Mean: 67


In [46]:
result = dataSet[:, 0] * dataSet[:, 2]
print("SepalLength x PetalLength:\n", result.reshape(15, 10))


SepalLength x PetalLength:
 [[ 7.14  6.86  6.11  6.9   7.    9.18  6.44  7.5   6.16  7.35]
 [ 8.1   7.68  6.72  4.73  6.96  8.55  7.02  7.14  9.69  7.65]
 [ 9.18  7.65  4.6   8.67  9.12  8.    8.    7.8   7.28  7.52]
 [ 7.68  8.1   7.8   7.7   7.35  6.    7.15  7.35  5.72  7.65]
 [ 6.5   5.85  5.72  8.    9.69  6.72  8.16  6.44  7.95  7.  ]
 [32.9  28.8  33.81 22.   29.9  25.65 29.61 16.17 30.36 20.28]
 [17.5  24.78 24.   28.67 20.16 29.48 25.2  23.78 27.9  21.84]
 [28.32 24.4  30.87 28.67 27.52 29.04 32.64 33.5  27.   19.95]
 [20.9  20.35 22.62 30.6  24.3  27.   31.49 27.72 22.96 22.  ]
 [24.2  28.06 23.2  16.5  23.52 23.94 23.94 26.66 15.3  23.37]
 [37.8  29.58 41.89 35.28 37.7  50.16 22.05 45.99 38.86 43.92]
 [33.15 33.92 37.4  28.5  29.58 33.92 35.75 51.59 53.13 30.  ]
 [39.33 27.44 51.59 30.87 38.19 43.2  29.76 29.89 35.84 41.76]
 [45.14 50.56 35.84 32.13 34.16 46.97 35.28 35.2  28.8  37.26]
 [37.52 35.19 29.58 40.12 38.19 34.84 31.5  33.8  33.48 30.09]]


In [47]:
batches = dataSet.reshape(5, 30, dataSet.shape[1])
print("Batches shape:", batches.shape)

Batches shape: (5, 30, 4)


In [ ]:
stacked = np.column_stack((dataSet[:, 0], dataSet[:, 2]))
print("Horizontally stacked shape:", stacked.shape)
print(stacked[:5])


Horizontally stacked shape: (150, 2)
[[5.1 1.4]
 [4.9 1.4]
 [4.7 1.3]
 [4.6 1.5]
 [5.  1.4]]


In [50]:
mask = dataSet[:, 3] < 0.5
filtered_rows = dataSet[mask]
print("Filtered rows where Petal Width < 0.5:\n", filtered_rows)


Filtered rows where Petal Width < 0.5:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]]
